-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 10:48:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projet_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` VARCHAR(200) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `categorie` VARCHAR(50) NOT NULL,
  `position` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compositions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `forme` VARCHAR(100) NOT NULL,
  `couleur` VARCHAR(100) NOT NULL,
  `fleur1` VARCHAR(100) NOT NULL,
  `fleur2` VARCHAR(100) NOT NULL,
  `herbe` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `userId` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
INSERT INTO customer (`userId`, `lastname`, `firstname`, `email`, `password`, `isAdmin`) 
VALUES ('admin', 'admin', 'admin', 'admin@admin.com', '$2y$10$1ho1ll7kJABk0S32yHzlJuVXdjY7Xre278Jp2zG8perBZKd.AndfK', 1);

-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `text` TEXT(200) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  INDEX `fk_Bouquet_has_Customers_Bouquet1_idx` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
